/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    blogs: Blog;
    tests: Test;
    media: Media;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
  };
  globals: {
    footer: Footer;
    header: Header;
  };
}
export interface User {
  id: string;
  name?: string;
  roles?: ('admin' | 'user')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Page {
  id: string;
  layout: (
    | {
        richTextBlockFields?: {
          align?: 'left' | 'center' | 'right';
          backgroundColor?: 'none' | 'white' | 'black';
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'richTextBlock';
      }
    | {
        heroBlockFields?: {
          gradiant?: boolean;
          layout?: 'left' | 'center' | 'right';
          color?: 'green' | 'black';
          slides?: {
            media: string | Media;
            title?: string;
            color?: 'grey' | 'green' | 'red';
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'heroBlock';
      }
    | {
        headerBannerBlockFields?: {
          headerBanner?: boolean;
          color?: 'green' | 'black';
          title?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'headerBannerBlock';
      }
    | {
        heroFullWidthBlockFields: {
          heroBanner?: boolean;
          layout?: 'left' | 'center' | 'right';
          color?: 'green' | 'black';
          enableMedia?: boolean;
          media: string | Media;
          enableIcon?: boolean;
          icon: string | Media;
          enableOverlayIcon?: boolean;
          overlayicon: string | Media;
          title?: string;
          text?: string;
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'heroFullWidthBlock';
      }
    | {
        cardCarouselBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          cards?: {
            color?: 'red' | 'green';
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            media: string | Media;
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cardCarouselBlock';
      }
    | {
        ourTeamBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          member?: {
            name?: string;
            linkedin?: string;
            job?: string;
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'ourTeamBlock';
      }
    | {
        sliderSplitBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          slides?: {
            media: string | Media;
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          enablePaginationButtons?: boolean;
        };
        id?: string;
        blockName?: string;
        blockType: 'sliderSplitBlock';
      }
    | {
        galleryBlockFields: {
          images: {
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'galleryBlock';
      }
    | {
        duskTestimonialsBlockFields?: {
          testimonials?: {
            testimonial: string;
            name: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'duskTestimonialsBlock';
      }
    | {
        contentBlockFields: {
          leftLayout: (
            | {
                quoteBlockFields: {
                  author?: string;
                  byline?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  media: string | Media;
                  color?: 'black' | 'red' | 'green';
                };
                id?: string;
                blockName?: string;
                blockType: 'quoteBlock';
              }
            | {
                standardBlockFields?: {
                  textPosition?: 'center' | 'left';
                  textSize?: 'small' | 'normal' | 'large';
                  title?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  enableLink?: boolean;
                  links?: {
                    link: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Test;
                            relationTo: 'tests';
                          }
                        | {
                            value: string | Blog;
                            relationTo: 'blogs';
                          };
                      url: string;
                      label: string;
                      appearance: string;
                    };
                    id?: string;
                  }[];
                };
                id?: string;
                blockName?: string;
                blockType: 'standardBlock';
              }
            | {
                mediaBlockFields: {
                  media: string | Media;
                  shadow?: 'select' | 'yes' | 'no';
                  shadowPosition?: 'select' | 'left' | 'right';
                };
                id?: string;
                blockName?: string;
                blockType: 'mediaBlock';
              }
          )[];
          rightLayout: (
            | {
                quoteBlockFields: {
                  author?: string;
                  byline?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  media: string | Media;
                  color?: 'black' | 'red' | 'green';
                };
                id?: string;
                blockName?: string;
                blockType: 'quoteBlock';
              }
            | {
                standardBlockFields?: {
                  textPosition?: 'center' | 'left';
                  textSize?: 'small' | 'normal' | 'large';
                  title?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  enableLink?: boolean;
                  links?: {
                    link: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Test;
                            relationTo: 'tests';
                          }
                        | {
                            value: string | Blog;
                            relationTo: 'blogs';
                          };
                      url: string;
                      label: string;
                      appearance: string;
                    };
                    id?: string;
                  }[];
                };
                id?: string;
                blockName?: string;
                blockType: 'standardBlock';
              }
            | {
                mediaBlockFields: {
                  media: string | Media;
                  shadow?: 'select' | 'yes' | 'no';
                  shadowPosition?: 'select' | 'left' | 'right';
                };
                id?: string;
                blockName?: string;
                blockType: 'mediaBlock';
              }
          )[];
          background?: 'none' | 'grey' | 'green';
          enableIcon?: boolean;
          icon?: string | Media;
          divider?: 'no' | 'yes';
        };
        id?: string;
        blockName?: string;
        blockType: 'contentBlock';
      }
    | {
        faqBlockFields?: {
          title?: string;
          questions?: {
            question?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'faqBlock';
      }
    | {
        fullPageBlockFields: {
          width?: 'small' | 'medium' | 'large';
          background?: 'none' | 'grey' | 'green';
          enableBgImage?: boolean;
          bgImage?: string | Media;
          divider?: 'no' | 'yes';
          enableIcon?: boolean;
          icon: string | Media;
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'fullPageBlock';
      }
    | {
        carouselBlockFields?: {
          background?: 'none' | 'green';
          icon?: string | Media;
          logo?: string | Media;
          image?: string | Media;
          style?: 'top' | 'left';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
          products?: {
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'carouselBlock';
      }
    | {
        customProductBlockFields?: {
          title?: string;
          elements?: {
            name?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'customProductBlock';
      }
    | {
        productBlockFields?: {
          products?: {
            media: string | Media;
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            features?: {
              feature?: string;
              id?: string;
            }[];
            background?: 'none' | 'green';
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'productBlock';
      }
    | {
        threeColProductBlockFields?: {
          enableIntro?: boolean;
          intro?: string;
          text?: string;
          enableBgIcons?: boolean;
          bgIcon?: string | Media;
          products?: {
            media: string | Media;
            title?: string;
            id?: string;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'threeColProductBlock';
      }
    | {
        fourBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          blocks?: {
            color?: 'red' | 'green';
            media: string | Media;
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'fourBlock';
      }
    | {
        timelineBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          dates?: {
            year?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'timelineBlock';
      }
    | {
        accreditationBlockFields?: {
          title?: string;
          accreditations?: {
            media: string | Media;
            title?: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'accreditationBlock';
      }
    | {
        breadcrumbsBlockFields?: {
          title?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'breadcrumbsBlock';
      }
    | {
        formFields: {
          title?: string;
          introContent?: {
            [k: string]: unknown;
          }[];
          form: string | Form;
        };
        contactFields?: {
          introContent?: {
            [k: string]: unknown;
          }[];
          contactMethods?: {
            icon?: string | Media;
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'contactBlock';
      }
    | {
        newsletterBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'newsletterBlock';
      }
    | {
        testimonialBlockFields?: {
          background?: 'none' | 'green';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          testimonials?: {
            background?: 'none' | 'green';
            color?: 'red' | 'green';
            title?: string;
            job?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'testimonialBlock';
      }
    | {
        videoBlockFields?: {
          background?: 'none' | 'green';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          embed?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'videoBlock';
      }
    | {
        tableCarouselBlockFields: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          testBenefits: string[] | Test[];
        };
        id?: string;
        blockName?: string;
        blockType: 'tableCarouselBlock';
      }
    | {
        getInTouchBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'getInTouchBlock';
      }
    | {
        testBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          background?: 'grey' | 'blue';
          tests?: {
            name?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            media: string | Media;
            enableLink?: boolean;
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'testBlock';
      }
    | {
        archiveBlockFields?: {
          background?: 'none' | 'grey';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          displayType?: 'carousel';
          populateBy?: 'collection' | 'selection';
          relationTo?: 'tests';
          limit?: number;
          populatedDocs?:
            | {
                value: string;
                relationTo: 'tests';
              }[]
            | {
                value: Test;
                relationTo: 'tests';
              }[];
          selectedDocs?:
            | {
                value: string;
                relationTo: 'tests';
              }[]
            | {
                value: Test;
                relationTo: 'tests';
              }[];
          populatedDocsTotal?: number;
        };
        id?: string;
        blockName?: string;
        blockType: 'archiveBlock';
      }
    | {
        blogArchiveBlockFields?: {
          background?: 'none' | 'grey';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          displayType?: 'carousel';
          populateBy?: 'collection' | 'selection';
          relationTo?: 'blogs';
          limit?: number;
          populatedDocs?:
            | {
                value: string;
                relationTo: 'blogs';
              }[]
            | {
                value: Blog;
                relationTo: 'blogs';
              }[];
          selectedDocs?:
            | {
                value: string;
                relationTo: 'blogs';
              }[]
            | {
                value: Blog;
                relationTo: 'blogs';
              }[];
          populatedDocsTotal?: number;
        };
        id?: string;
        blockName?: string;
        blockType: 'blogArchiveBlock';
      }
    | {
        cmxCarouselBlockFields?: {
          background?: 'none' | 'green';
          icon?: string | Media;
          logo?: string | Media;
          image?: string | Media;
          style?: 'top' | 'left';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
          products?: {
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'cmxCarouselBlock';
      }
    | {
        privateLabelingBlockFields?: {
          background?: 'none' | 'green';
          icon?: string | Media;
          logo?: string | Media;
          image?: string | Media;
          style?: 'top' | 'left';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          enableLink?: boolean;
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
          products?: {
            media: string | Media;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'privateLabelingBlock';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  title: string;
  publishedDate?: string;
  slug?: string;
  parent?: string | Page;
  breadcrumbs?: {
    doc?: string | Page;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Test {
  id: string;
  title: string;
  subheading: string;
  richText?: {
    [k: string]: unknown;
  }[];
  shortDescription: string;
  media: string | Media;
  color?: 'red' | 'green';
  benefits: {
    name: string;
    enabled?: boolean;
    id?: string;
  }[];
  layout: (
    | {
        contentBlockFields: {
          leftLayout: (
            | {
                quoteBlockFields: {
                  author?: string;
                  byline?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  media: string | Media;
                  color?: 'black' | 'red' | 'green';
                };
                id?: string;
                blockName?: string;
                blockType: 'quoteBlock';
              }
            | {
                standardBlockFields?: {
                  textPosition?: 'center' | 'left';
                  textSize?: 'small' | 'normal' | 'large';
                  title?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  enableLink?: boolean;
                  links?: {
                    link: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Test;
                            relationTo: 'tests';
                          }
                        | {
                            value: string | Blog;
                            relationTo: 'blogs';
                          };
                      url: string;
                      label: string;
                      appearance: string;
                    };
                    id?: string;
                  }[];
                };
                id?: string;
                blockName?: string;
                blockType: 'standardBlock';
              }
            | {
                mediaBlockFields: {
                  media: string | Media;
                  shadow?: 'select' | 'yes' | 'no';
                  shadowPosition?: 'select' | 'left' | 'right';
                };
                id?: string;
                blockName?: string;
                blockType: 'mediaBlock';
              }
          )[];
          rightLayout: (
            | {
                quoteBlockFields: {
                  author?: string;
                  byline?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  media: string | Media;
                  color?: 'black' | 'red' | 'green';
                };
                id?: string;
                blockName?: string;
                blockType: 'quoteBlock';
              }
            | {
                standardBlockFields?: {
                  textPosition?: 'center' | 'left';
                  textSize?: 'small' | 'normal' | 'large';
                  title?: string;
                  richText?: {
                    [k: string]: unknown;
                  }[];
                  enableLink?: boolean;
                  links?: {
                    link: {
                      type?: 'reference' | 'custom';
                      newTab?: boolean;
                      reference:
                        | {
                            value: string | Page;
                            relationTo: 'pages';
                          }
                        | {
                            value: string | Test;
                            relationTo: 'tests';
                          }
                        | {
                            value: string | Blog;
                            relationTo: 'blogs';
                          };
                      url: string;
                      label: string;
                      appearance: string;
                    };
                    id?: string;
                  }[];
                };
                id?: string;
                blockName?: string;
                blockType: 'standardBlock';
              }
            | {
                mediaBlockFields: {
                  media: string | Media;
                  shadow?: 'select' | 'yes' | 'no';
                  shadowPosition?: 'select' | 'left' | 'right';
                };
                id?: string;
                blockName?: string;
                blockType: 'mediaBlock';
              }
          )[];
          background?: 'none' | 'grey' | 'green';
          enableIcon?: boolean;
          icon?: string | Media;
          divider?: 'no' | 'yes';
        };
        id?: string;
        blockName?: string;
        blockType: 'contentBlock';
      }
    | {
        faqBlockFields?: {
          title?: string;
          questions?: {
            question?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'faqBlock';
      }
    | {
        videoBlockFields?: {
          background?: 'none' | 'green';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          embed?: string;
        };
        id?: string;
        blockName?: string;
        blockType: 'videoBlock';
      }
    | {
        newsletterBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'newsletterBlock';
      }
    | {
        sliderSplitBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          slides?: {
            media: string | Media;
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
          enablePaginationButtons?: boolean;
        };
        id?: string;
        blockName?: string;
        blockType: 'sliderSplitBlock';
      }
    | {
        testimonialBlockFields?: {
          background?: 'none' | 'green';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          testimonials?: {
            background?: 'none' | 'green';
            color?: 'red' | 'green';
            title?: string;
            job?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'testimonialBlock';
      }
    | {
        accreditationBlockFields?: {
          title?: string;
          accreditations?: {
            media: string | Media;
            title?: string;
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'accreditationBlock';
      }
    | {
        getInTouchBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          links?: {
            link: {
              type?: 'reference' | 'custom';
              newTab?: boolean;
              reference:
                | {
                    value: string | Page;
                    relationTo: 'pages';
                  }
                | {
                    value: string | Test;
                    relationTo: 'tests';
                  }
                | {
                    value: string | Blog;
                    relationTo: 'blogs';
                  };
              url: string;
              label: string;
              appearance: string;
            };
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'getInTouchBlock';
      }
    | {
        productBlockFields?: {
          products?: {
            media: string | Media;
            title?: string;
            richText?: {
              [k: string]: unknown;
            }[];
            features?: {
              feature?: string;
              id?: string;
            }[];
            background?: 'none' | 'green';
            links?: {
              link: {
                type?: 'reference' | 'custom';
                newTab?: boolean;
                reference:
                  | {
                      value: string | Page;
                      relationTo: 'pages';
                    }
                  | {
                      value: string | Test;
                      relationTo: 'tests';
                    }
                  | {
                      value: string | Blog;
                      relationTo: 'blogs';
                    };
                url: string;
                label: string;
                appearance: string;
              };
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'productBlock';
      }
    | {
        archiveBlockFields?: {
          background?: 'none' | 'grey';
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          displayType?: 'carousel';
          populateBy?: 'collection' | 'selection';
          relationTo?: 'tests';
          limit?: number;
          populatedDocs?:
            | {
                value: string;
                relationTo: 'tests';
              }[]
            | {
                value: Test;
                relationTo: 'tests';
              }[];
          selectedDocs?:
            | {
                value: string;
                relationTo: 'tests';
              }[]
            | {
                value: Test;
                relationTo: 'tests';
              }[];
          populatedDocsTotal?: number;
        };
        id?: string;
        blockName?: string;
        blockType: 'archiveBlock';
      }
    | {
        comparisonBlockFields?: {
          title?: string;
          richText?: {
            [k: string]: unknown;
          }[];
          tableHeading?: string;
          columns?: {
            title: string;
            color?: 'red' | 'green';
            rows: {
              name: string;
              dataType?: 'checkbox' | 'text';
              enabled?: boolean;
              text: string;
              id?: string;
            }[];
            id?: string;
          }[];
        };
        id?: string;
        blockName?: string;
        blockType: 'comparisonBlock';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  publishedDate?: string;
  slug?: string;
  parent?: string | Test;
  breadcrumbs?: {
    doc?: string | Test;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Media {
  id: string;
  alt: string;
  caption?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
}
export interface Blog {
  id: string;
  title: string;
  subheading: string;
  richText?: {
    [k: string]: unknown;
  }[];
  shortDescription: string;
  media: string | Media;
  color?: 'red' | 'green';
  layout: {
    richTextBlockFields?: {
      align?: 'left' | 'center' | 'right';
      backgroundColor?: 'none' | 'white' | 'black';
      richText?: {
        [k: string]: unknown;
      }[];
      enableLink?: boolean;
      links?: {
        link: {
          type?: 'reference' | 'custom';
          newTab?: boolean;
          reference:
            | {
                value: string | Page;
                relationTo: 'pages';
              }
            | {
                value: string | Test;
                relationTo: 'tests';
              }
            | {
                value: string | Blog;
                relationTo: 'blogs';
              };
          url: string;
          label: string;
          appearance: string;
        };
        id?: string;
      }[];
    };
    id?: string;
    blockName?: string;
    blockType: 'richTextBlock';
  }[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  publishedDate?: string;
  slug?: string;
  parent?: string | Blog;
  breadcrumbs?: {
    doc?: string | Blog;
    url?: string;
    label?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Form {
  id: string;
  title: string;
  fields?: (
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        placeholder?: string;
        id?: string;
        blockName?: string;
        blockType: 'text';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        required?: boolean;
        placeholder?: string;
        id?: string;
        blockName?: string;
        blockType: 'textarea';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: string;
        options?: {
          label: string;
          value: string;
          id?: string;
        }[];
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'select';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'email';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'state';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'country';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        defaultValue?: number;
        required?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'number';
      }
    | {
        name: string;
        label?: string;
        width?: number;
        required?: boolean;
        defaultValue?: boolean;
        id?: string;
        blockName?: string;
        blockType: 'checkbox';
      }
    | {
        message?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'message';
      }
  )[];
  submitButtonLabel?: string;
  confirmationType?: 'message' | 'redirect';
  confirmationMessage: {
    [k: string]: unknown;
  }[];
  redirect?: {
    url: string;
  };
  emails?: {
    emailTo?: string;
    cc?: string;
    bcc?: string;
    replyTo?: string;
    emailFrom?: string;
    subject: string;
    message?: {
      [k: string]: unknown;
    }[];
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Redirect {
  id: string;
  from: string;
  to: {
    type?: 'reference' | 'custom';
    reference:
      | {
          value: string | Page;
          relationTo: 'pages';
        }
      | {
          value: string | Blog;
          relationTo: 'blogs';
        }
      | {
          value: string | Test;
          relationTo: 'tests';
        };
    url: string;
  };
  updatedAt: string;
  createdAt: string;
}
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?: {
    field: string;
    value: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Footer {
  id: string;
  navItems?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference:
        | {
            value: string | Page;
            relationTo: 'pages';
          }
        | {
            value: string | Test;
            relationTo: 'tests';
          }
        | {
            value: string | Blog;
            relationTo: 'blogs';
          };
      url: string;
      label: string;
    };
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
export interface Header {
  id: string;
  navItems?: {
    link: {
      type?: 'reference' | 'custom';
      newTab?: boolean;
      reference:
        | {
            value: string | Page;
            relationTo: 'pages';
          }
        | {
            value: string | Test;
            relationTo: 'tests';
          }
        | {
            value: string | Blog;
            relationTo: 'blogs';
          };
      url: string;
      label: string;
    };
    subNavItems?: {
      link: {
        type?: 'reference' | 'custom';
        newTab?: boolean;
        reference:
          | {
              value: string | Page;
              relationTo: 'pages';
            }
          | {
              value: string | Test;
              relationTo: 'tests';
            }
          | {
              value: string | Blog;
              relationTo: 'blogs';
            };
        url: string;
        label: string;
      };
      id?: string;
    }[];
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
